package com.genixo.ges.languagecamp.model;

public enum EProjectType {
    INTERNATIONAL_TRIP,
    LOCAL_TRIP,
    INTERNATIONAL_SUMMER_SCHOOL,
    INTERNATIONAL_EDUCATION,
    INTERNATIONAL_HIGH_SCHOOL,
    INTERNATIONAL_UNIVERSITY,
    INTERNATIONAL_TRAVEL_INSURANCE
}

