CREATE TABLE portal_home_page_content (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    badge_text VARCHAR(255) NOT NULL,
    hero_title VARCHAR(512) NOT NULL,
    hero_description TEXT NOT NULL,
    hero_primary_cta_text VARCHAR(128) NOT NULL,
    hero_secondary_cta_text VARCHAR(128) NOT NULL,
    feature1_title VARCHAR(128) NOT NULL,
    feature1_description TEXT NOT NULL,
    feature2_title VARCHAR(128) NOT NULL,
    feature2_description TEXT NOT NULL,
    feature3_title VARCHAR(128) NOT NULL,
    feature3_description TEXT NOT NULL,
    hero_image_url VARCHAR(1024),
    sidebar_image1_url VARCHAR(1024),
    sidebar_image2_url VARCHAR(1024),
    sidebar_card_title VARCHAR(255) NOT NULL,
    sidebar_card_description TEXT NOT NULL,
    sidebar_card_primary_cta_text VARCHAR(128) NOT NULL,
    sidebar_card_secondary_cta_text VARCHAR(128) NOT NULL,
    about_section_label VARCHAR(128) NOT NULL,
    about_section_title VARCHAR(255) NOT NULL,
    about_section_cta_text VARCHAR(128) NOT NULL,
    about_feature1_title VARCHAR(128) NOT NULL,
    about_feature1_description TEXT NOT NULL,
    about_feature2_title VARCHAR(128) NOT NULL,
    about_feature2_description TEXT NOT NULL,
    about_feature3_title VARCHAR(128) NOT NULL,
    about_feature3_description TEXT NOT NULL,
    process_section_title VARCHAR(255) NOT NULL,
    process_step1_title VARCHAR(128) NOT NULL,
    process_step1_description TEXT NOT NULL,
    process_step2_title VARCHAR(128) NOT NULL,
    process_step2_description TEXT NOT NULL,
    process_step3_title VARCHAR(128) NOT NULL,
    process_step3_description TEXT NOT NULL,
    process_image_url VARCHAR(1024),
    process_image_caption TEXT,
    gallery_section_label VARCHAR(128) NOT NULL,
    gallery_section_title VARCHAR(255) NOT NULL,
    gallery_section_cta_text VARCHAR(128) NOT NULL,
    gallery_image1_url VARCHAR(1024),
    gallery_image2_url VARCHAR(1024),
    gallery_image3_url VARCHAR(1024),
    gallery_image4_url VARCHAR(1024),
    gallery_image5_url VARCHAR(1024),
    gallery_image6_url VARCHAR(1024)
);

INSERT INTO portal_home_page_content (
    id,
    created_at,
    updated_at,
    badge_text,
    hero_title,
    hero_description,
    hero_primary_cta_text,
    hero_secondary_cta_text,
    feature1_title,
    feature1_description,
    feature2_title,
    feature2_description,
    feature3_title,
    feature3_description,
    hero_image_url,
    sidebar_image1_url,
    sidebar_image2_url,
    sidebar_card_title,
    sidebar_card_description,
    sidebar_card_primary_cta_text,
    sidebar_card_secondary_cta_text,
    about_section_label,
    about_section_title,
    about_section_cta_text,
    about_feature1_title,
    about_feature1_description,
    about_feature2_title,
    about_feature2_description,
    about_feature3_title,
    about_feature3_description,
    process_section_title,
    process_step1_title,
    process_step1_description,
    process_step2_title,
    process_step2_description,
    process_step3_title,
    process_step3_description,
    process_image_url,
    process_image_caption,
    gallery_section_label,
    gallery_section_title,
    gallery_section_cta_text,
    gallery_image1_url,
    gallery_image2_url,
    gallery_image3_url,
    gallery_image4_url,
    gallery_image5_url,
    gallery_image6_url
) VALUES (
    'a0000000-0000-4000-8000-000000000001',
    now(),
    now(),
    '2026 Dönemi Başvuruları Açık',
    'Yurt dışı dil kampına başvurunu kolayca tamamla.',
    'GES ile program seçimi, evrak hazırlığı ve başvuru sürecini tek ekrandan yönet. Başvurunu oluştur, gerekli belgeleri yükle, durumunu adım adım takip et.',
    'Başvuruyu Başlat',
    'Programı İncele',
    'Hızlı Başvuru',
    'Dakikalar içinde formu tamamla, süreci başlat.',
    'Evrak Yönetimi',
    'Gerekli belgeleri tek yerden yükle ve takip et.',
    'Durum Takibi',
    'Başvurunun hangi aşamada olduğunu anlık gör.',
    NULL,
    NULL,
    NULL,
    'Dil Kampı Başvurusu',
    'Başvuru oluşturduktan sonra evraklarını yükleyebilir ve değerlendirme sürecini panelden takip edebilirsin.',
    'Başvur',
    'Giriş',
    'Program Hakkında',
    'Neler sunuyoruz?',
    'Başvuru Formu',
    'Program Seçimi',
    'Hedef ülke ve kamp seçeneklerini incele, sana en uygun programı belirle.',
    'Evrak Kontrolü',
    'Belgeleri doğru formatta topla, eksik/yanlışları hızlıca tamamla.',
    'Şeffaf Süreç',
    'Başvurunun durumunu ve sonraki adımı panelde net şekilde gör.',
    'Süreç nasıl ilerliyor?',
    '1) Başvuru Oluştur',
    'Kısa formu doldur ve başvurunu başlat.',
    '2) Belgeleri Yükle',
    'Gerekli evrakları yükle, eksikleri tamamla.',
    '3) Değerlendirme & Bilgilendirme',
    'Başvurun incelenir; durum güncellemelerini panelden takip edersin.',
    NULL,
    'Not: Görselleri daha sonra buraya ekleyebiliriz (kamp fotoğrafları, etkinlikler, sınıf ortamı, şehir/ülke).',
    'Görsel Galeri',
    'Atmosferi hisset',
    'Hemen Başvur',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
);
